networks:
  edge:
    driver: bridge
    ipam:
      config:
        - subnet: ${EDGE_SUBNET}
  vps_net:
    driver: bridge
    ipam:
      config:
        - subnet: ${VPS_SUBNET}
  backend_net:
    driver: bridge
    ipam:
      config:
        - subnet: ${BACNKEND_SUBNET}
  local_b:
    driver: bridge
    ipam:
      config:
        - subnet: ${LOCAL_B_SUBNET}

services:
  router:
    build:
      dockerfile_inline: |
        FROM alpine:3.22.4
        RUN apk update
        RUN apk add iptables iproute2 tcpdump curl wget procps net-tools iputils-ping
    image: router
    profiles: ["build"]
  browserpup:
    build:
      dockerfile_inline: |
        FROM ghcr.io/puppeteer/puppeteer:25.1.0
        USER root
        RUN apt update 
        RUN apt install -y gosu
        RUN apt install -y iptables iproute2 tcpdump curl wget procps net-tools iputils-ping
    image: browserpup
    profiles: ["build"]
  sigturn_img:
    build:
      dockerfile_inline: |
        FROM debian:12.0-slim
        RUN apt update
        RUN apt install -y gosu
        RUN apt install -y nginx coturn
        RUN apt install -y gettext-base
        RUN apt install -y iptables iproute2 tcpdump curl wget procps net-tools iputils-ping
    image: sigturn_img
    profiles: ["build"]
  vps_front:
    image: router
    tty: true
    stdin_open: true
    hostname: ${VPS_FRONT_NAME}
    container_name: ${VPS_FRONT_NAME}
    cap_add:
      - NET_ADMIN
    entrypoint:
      - /bin/sh
      - -c
      - |
        echo 1 > /proc/sys/net/ipv4/ip_forward
        iptables -t nat -A PREROUTING -i ${VPS_FRONT_EDGE_NIF} -j DNAT --to-destination ${SIGTURN_IP}
        iptables -t nat -A POSTROUTING -o ${VPS_FRONT_EDGE_NIF} -j MASQUERADE
        tail -f /dev/null
    networks:
      edge:
        interface_name: ${VPS_FRONT_EDGE_NIF}
        ipv4_address: ${VPS_EDGE_IP}
      vps_net:
        interface_name: ${VPS_FRONT_NIF}
        ipv4_address: ${VPS_FRONT_LOCAL_ADDR}
  sigturn:
    image: sigturn_img
    tty: true
    stdin_open: true
    hostname: ${SIGTURN_NAME}
    container_name: ${SIGTURN_NAME}
    cap_add:
      - NET_ADMIN
    entrypoint:
      - /bin/sh
      - -c
      - |
        ip route add ${EDGE_SUBNET} via ${VPS_FRONT_LOCAL_ADDR}
        envsubst < /etc/coturn/turnserver.conf.template > /etc/turnserver.conf
        turnserver --daemon
        /signalling_server
        tail -f /dev/null
    environment:
      - COTURN_PORT=${COTURN_PORT}
      - VPS_EDGE_IP=${VPS_EDGE_IP}
      - VPS_FRONT_LOCAL_ADDR=${VPS_FRONT_LOCAL_ADDR}
      - VPS_FRONT_NAME=${VPS_FRONT_NAME}
      - SIGTURN_IP=${SIGTURN_IP}
      - STUN_CREDENTIALS=${STUN_CREDENTIALS}
      - SS_PORT=${SS_PORT}
      - SS_ADDR=0.0.0.0
    volumes:
      - ./test/turn/turnserver.conf.template:/etc/coturn/turnserver.conf.template
      - ./src-tauri/target/debug/signalling_server:/signalling_server
      - ./src-tauri/target/debug/:/targets
    networks:
      vps_net:
        ipv4_address: ${SIGTURN_IP}
    depends_on:
      - vps_front
   
  nat_b:
    image: router
    tty: true
    stdin_open: true
    container_name: ${NAT_B_NAME}
    cap_add:
      - NET_ADMIN
    entrypoint: ["/bin/sh", "/configure_nat_node.sh", "${NAT_B_NIF}", "${NAT_B_EDGE_NIF}"]
    volumes:
      - ./configure_nat_node.sh:/configure_nat_node.sh
    networks:
      local_b:
        interface_name: ${NAT_B_NIF}
        ipv4_address: ${NAT_B_ADDR}
      edge:
        interface_name: ${NAT_B_EDGE_NIF}
  browser:
    image: browserpup
    container_name: ${BROWSER_NAME}
    tty: true
    stdin_open: true
    cap_add:
      - NET_ADMIN
    entrypoint:
      - /bin/sh
      - -c
      - |
        ip route add ${EDGE_SUBNET} via ${NAT_B_ADDR}
        exec gosu pptruser sh -c "cp /browser/test.js ~/test.js; cp /browser/package.json ~/package.json; npm run test"
    volumes:
      - ./test/browser:/browser
    environment:
      - COTURN_PORT=${COTURN_PORT}
      - COTURN_IP=${VPS_EDGE_IP}
      - WS_URL=ws://${VPS_EDGE_IP}:${SS_PORT}
      - STUN_CREDENTIALS=${STUN_CREDENTIALS}
      - RTC_SESSION_ID=${RTC_SESSION_ID}
    networks:
      - local_b
    depends_on:
      - nat_b
  nat_backend:
    image: router
    tty: true
    stdin_open: true
    container_name: ${NAT_A_NAME}
    cap_add:
      - NET_ADMIN
    entrypoint: ["/bin/sh", "/configure_nat_node.sh", "${NAT_A_NIF}", "${NAT_A_EDGE_NIF}"]
    volumes:
      - ./configure_nat_node.sh:/configure_nat_node.sh
    networks:
      backend_net:
        interface_name: ${NAT_A_NIF}
        ipv4_address: ${NAT_A_ADDR}
      edge:
        interface_name: ${NAT_A_EDGE_NIF}
  
  backend:
    image: sigturn_img
    container_name: ${BACKEND_NAME}
    tty: true
    stdin_open: true
    cap_add:
      - NET_ADMIN
    entrypoint:
      - /bin/sh
      - -c
      - |
        ip route add ${EDGE_SUBNET} via ${NAT_A_ADDR}
        useradd --system --shell /usr/sbin/nologin --no-create-home appuser
        chown -R appuser:appuser /rtc_client_test
        exec gosu appuser sh -c "/rtc_client_test; tail -f /dev/null"
    environment:
      - COTURN_PORT=${COTURN_PORT}
      - COTURN_IP=${VPS_EDGE_IP}
      - SS_URL=ws://${VPS_EDGE_IP}:${SS_PORT}
      - STUN_CREDENTIALS=${STUN_CREDENTIALS}
      - RTC_SESSION_ID=${RTC_SESSION_ID}
      - RUST_LOG=info
      - RUST_BACKTRACE=1
    volumes:
      - ./src-tauri/target/debug/rtc_client_test:/rtc_client_test
    networks:
      - backend_net
    depends_on:
      - nat_backend