// This file has been generated by Specta. Do not edit this file manually.
/**  Strongly-typed filter names accepted by `get_tracks_filtered`. */
export type CriteriaName = "id" | "artist" | "track_name" | "length_seconds" | "bitrate_kbps" | "tempo_bpm" | "addition_time" | "tags";

export type FilterNumericOperator = "<" | ">" | "=" | "<=" | ">=" | "!=";

export type FilterSearchParam = { mode: "numeric_comparison"; operator: FilterNumericOperator; value: number | null } | { mode: "numeric_between"; min: number | null; max: number | null } | { mode: "text_like"; pattern: string; case_sensitive: boolean } | { mode: "text_in"; values: string[] } | { mode: "null_check"; is_null: boolean } | { mode: "tags_any"; tag_ids: number[] } | { mode: "tags_all"; tag_ids: number[] };

/**  Like `SearchCriteria` but with a typed `CriteriaName` and specta-exported params. */
export type SearchCriteriaFiltered = {
	filter_name: CriteriaName,
	criteria: FilterSearchParam[],
};
