// Auto-generated by specta.
// Regenerate with: cargo test -p vampagent export_bindings -- --nocapture
// (run from src-tauri/)

export type CriteriaName =
  | "id"
  | "artist"
  | "track_name"
  | "length_seconds"
  | "bitrate_kbps"
  | "tempo_bpm"
  | "addition_time"
  | "tags"

type NumericOperator = "<" | ">" | "=" | "<=" | ">=" | "!="

type SearchParam =
  | { mode: "numeric_comparison"; operator: NumericOperator; value: number }
  | { mode: "numeric_between"; min: number; max: number }
  | { mode: "text_like"; pattern: string; case_sensitive: boolean }
  | { mode: "text_in"; values: string[] }
  | { mode: "null_check"; is_null: boolean }
  | { mode: "tags_in"; tag_ids: number[] }
  | { mode: "tags_all"; tag_ids: number[] }

export type SearchCriteriaFiltered = {
  filter_name: CriteriaName
  criteria: SearchParam[]
}
