// This file has been generated by Specta. Do not edit this file manually.
export type AddListenArgs = {
	track_id: BigintId,
	from: string,
	to: string,
};

export type AddListenedSecondsArgs = {
	track_id: BigintId,
	seconds: number,
};

export type AddMetaArgs = {
	track_id: BigintId,
	key: string,
	value: string,
};

export type AddTrackSourceArgs = {
	track_id: BigintId,
	url: string,
};

export type AssignTagArgs = {
	track_id: BigintId,
	tag_id: BigintId,
};

/**
 *  A 64-bit integer ID serialised as a string for safe JavaScript interop.
 * 
 *  JavaScript's `number` type cannot safely represent integers beyond 2^53 - 1,
 *  so database row IDs (SQLite BIGINT / i64) are transmitted as decimal strings.
 * 
 *  On the Rust side, use [`BigintId::to_i64`] before binding to a SQL query.
 *  SQLite rows that derive [`sqlx::FromRow`] convert automatically via the
 *  `#[sqlx(try_from = "i64")]` attribute on each field.
 */
export type BigintId = string;

/**
 *  Discriminated union of every DB operation.
 *  JS serialises as `{ "kind": "<VariantName>", "payload": <args> }`.
 */
export type Command = { kind: "AddTrack"; payload: NewTrack } | { kind: "AddTracks"; payload: NewTrack[] } | { kind: "UpdateTrack"; payload: UpdateTrackArgs } | { kind: "GetTracks"; payload: GetTracksArgs } | { kind: "GetTracksWithSources"; payload: GetTracksArgs } | { kind: "GetTracksFiltered"; payload: GetTracksFilteredArgs } | { kind: "GetTrack"; payload: IdArg } | { kind: "DeleteTrack"; payload: IdArg } | { kind: "AddListen"; payload: AddListenArgs } | { kind: "GetListensForTrack"; payload: TrackIdArg } | { kind: "AddListenedSeconds"; payload: AddListenedSecondsArgs } | { kind: "AddTag"; payload: NameArg } | { kind: "EditTag"; payload: EditTagArgs } | { kind: "DeleteTag"; payload: IdArg } | { kind: "GetAllTags"; payload: null } | { kind: "GetTags"; payload: PatternArg } | { kind: "AssignTag"; payload: AssignTagArgs } | { kind: "AssignTags"; payload: TagAssignment[] } | { kind: "RemoveTag"; payload: AssignTagArgs } | { kind: "GetTagsForTrack"; payload: TrackIdArg } | { kind: "AddMeta"; payload: AddMetaArgs } | { kind: "UpdateMeta"; payload: UpdateMetaArgs } | { kind: "DeleteMeta"; payload: IdArg } | { kind: "GetMetaForTrack"; payload: TrackIdArg } | { kind: "AddTrackSource"; payload: AddTrackSourceArgs } | { kind: "RemoveTrackSource"; payload: RemoveTrackSourceArgs } | { kind: "EditTrackSource"; payload: EditTrackSourceArgs } | { kind: "GetSourcesForTrack"; payload: TrackIdArg } | { kind: "GetHtmlBundle"; payload: null } | { kind: "LogFromUi"; payload: LogFromUiArgs };

/**  Strongly-typed filter names accepted by `get_tracks_filtered`. */
export type CriteriaName = "id" | "artist" | "track_name" | "length_seconds" | "bitrate_kbps" | "tempo_bpm" | "addition_time" | "tags" | "listened_seconds";

export type EditTagArgs = {
	id: BigintId,
	name: string,
};

export type EditTrackSourceArgs = {
	track_id: BigintId,
	old_url: string,
	new_url: string,
};

export type FilterNumericOperator = "<" | ">" | "=" | "<=" | ">=" | "!=";

export type FilterSearchParam = { mode: "numeric_comparison"; operator: FilterNumericOperator; value: number | null } | { mode: "numeric_between"; min: number | null; max: number | null } | { mode: "text_like"; pattern: string; case_sensitive: boolean } | { mode: "text_in"; values: string[] } | { mode: "null_check"; is_null: boolean } | { mode: "tags_any"; tag_ids: BigintId[] } | { mode: "tags_all"; tag_ids: BigintId[] };

export type GetTracksArgs = {
	cursor: BigintId | null,
	criteria: SearchCriteria[] | null,
	limit: number,
};

export type GetTracksFilteredArgs = {
	cursor: BigintId | null,
	criteria: SearchCriteriaFiltered[] | null,
	limit: number,
};

export type IdArg = {
	id: BigintId,
};

export type LogFromUiArgs = {
	message: string,
};

export type NameArg = {
	name: string,
};

/**  Input for inserting a new track. */
export type NewTrack = {
	artist: string,
	track_name: string,
	length_seconds: number | null,
	bitrate_kbps: number | null,
	tempo_bpm: number | null,
	addition_time: string,
	sources: string[],
};

export type NumericOperator = "<" | ">" | "=" | "<=" | ">=" | "!=";

export type PatternArg = {
	pattern: string,
};

export type RemoveTrackSourceArgs = {
	track_id: BigintId,
	url: string,
};

export type SearchCriteria = {
	column_name: string,
	criteria: SearchParam[],
};

/**  Like `SearchCriteria` but with a typed `CriteriaName` and specta-exported params. */
export type SearchCriteriaFiltered = {
	filter_name: CriteriaName,
	criteria: FilterSearchParam[],
};

export type SearchParam = { mode: "numeric_comparison"; operator: NumericOperator; value: number | null } | { mode: "numeric_between"; min: number | null; max: number | null } | { mode: "text_like"; pattern: string; case_sensitive: boolean } | { mode: "text_in"; values: string[] } | { mode: "null_check"; is_null: boolean } | 
/**
 *  Filter tracks by tag IDs. Use with `column_name = "tags"`.
 *  Returns tracks that have at least one of the provided tag IDs assigned.
 */
{ mode: "tags_in"; tag_ids: BigintId[] } | 
/**  Like TagsIn, but only returns tracks that have ALL of the provided tag IDs assigned. */
{ mode: "tags_all"; tag_ids: BigintId[] };

/**  Input for `assign_tags`: one track paired with the tag IDs to assign to it. */
export type TagAssignment = {
	track_id: BigintId,
	tag_ids: BigintId[],
};

export type TrackIdArg = {
	track_id: BigintId,
};

/**
 *  Partial update — only `Some` fields are written to the database.
 *  Pass `None` for any field that should remain unchanged.
 */
export type TrackUpdate = {
	artist: string | null,
	track_name: string | null,
	length_seconds: number | null,
	bitrate_kbps: number | null,
	tempo_bpm: number | null,
	addition_time: string | null,
};

export type UpdateMetaArgs = {
	id: BigintId,
	value: string,
};

export type UpdateTrackArgs = {
	id: BigintId,
	update: TrackUpdate,
};

export type WsRequest = {
	id: string,
	kind: string,
	cmd: Command,
};

export type WsResponse<T> = {
	id: string,
	result: WsResult<T>,
};

export type WsResult<T> = { type: "ok"; value: T } | { type: "error"; message: string };
