// This file has been generated by Specta. Do not edit this file manually.
export type SignalKind = "offer" | "answer" | "ice-candidate" | "local-candidate";

export type SignalMsg = {
	type: SignalKind,
	sdp: string,
	neg_id: string,
};

export type TransportMsg<T> = { type: "ack"; sn: number; node_id: string } | { type: "normal"; sn: number; node_id: string; payload: T };

export type WireMsg<T> = {
	tag: string,
	message: TransportMsg<T> | null,
};
